### ISSUE TITLE
System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by kburnik** [tamasflamich/effort#10]
Just to emphasize, codeplex currently doesn't support adding new threads to issue or discussion board, otherwise I would post this issue there. 

This simple test fails on any attempt to work with DbSet. 

```
public async Task TestMethod1()
{
    DbConnection inMemoryConnection =                
        Effort.DbConnectionFactory.CreateTransient();

    using (var dbContext = MyDbContext.CreateDbContext(inMemoryConnection)) 
    {
        // Fails on this line (triggered by Add method):
        dbContext.Users.Add(new User()
        {
            Id = 1                         
        });
        var item = dbContext.User.Find(1);
        Assert.AreEqual(1, item.Id);
    } 
}
```

Tried Methods like Add, Find, FindAsync, linq queries, etc. Also tried with a couple of even simpler entities. Tried using IDbSet as well. Also played around with the app.config and finally removed any references to Effort from the config in regards to DB connection.

I have no idea what I'm missing... Any suggestions?

Top exception is:

***System.InvalidOperationException: Sequence contains no matching element***

```
Test Name:	TestMethod1
Test FullName:	****
Test Source:	**** : line 21
Test Outcome:	Failed
Test Duration:	0:00:00,5738216

Result Message:	
Test method ****.TestMethod1 threw exception: 
System.InvalidOperationException: Sequence contains no matching element
Result StackTrace:	
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Data.Entity.Utilities.DbProviderManifestExtensions.GetStoreTypeFromName(DbProviderManifest providerManifest, String name)
   at System.Data.Entity.ModelConfiguration.Configuration.Properties.Primitive.PrimitivePropertyConfiguration.ConfigureColumn(EdmProperty column, EntityType table, DbProviderManifest providerManifest)
   at System.Data.Entity.ModelConfiguration.Configuration.Properties.Primitive.PrimitivePropertyConfiguration.Configure(EdmProperty column, EntityType table, DbProviderManifest providerManifest, Boolean allowOverride, Boolean fillFromExistingConfiguration)
   at System.Data.Entity.ModelConfiguration.Configuration.Properties.Primitive.PrimitivePropertyConfiguration.<>c__DisplayClass4.<Configure>b__3(Tuple`2 pm)
   at System.Data.Entity.Utilities.IEnumerableExtensions.Each[T](IEnumerable`1 ts, Action`1 action)
   at System.Data.Entity.ModelConfiguration.Configuration.Properties.Primitive.PrimitivePropertyConfiguration.Configure(IEnumerable`1 propertyMappings, DbProviderManifest providerManifest, Boolean allowOverride, Boolean fillFromExistingConfiguration)
   at System.Data.Entity.ModelConfiguration.Configuration.Types.StructuralTypeConfiguration.ConfigurePropertyMappings(IList`1 propertyMappings, DbProviderManifest providerManifest, Boolean allowOverride)
   at System.Data.Entity.ModelConfiguration.Configuration.Types.EntityTypeConfiguration.ConfigurePropertyMappings(DbDatabaseMapping databaseMapping, EntityType entityType, DbProviderManifest providerManifest, Boolean allowOverride)
   at System.Data.Entity.ModelConfiguration.Configuration.Types.EntityTypeConfiguration.Configure(EntityType entityType, DbDatabaseMapping databaseMapping, DbProviderManifest providerManifest)
   at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.ConfigureEntityTypes(DbDatabaseMapping databaseMapping, ICollection`1 entitySets, DbProviderManifest providerManifest)
   at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.Configure(DbDatabaseMapping databaseMapping, DbProviderManifest providerManifest)
   at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
   at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   at System.Data.Entity.DbSet`1.Add(TEntity entity)
   at ****.<TestMethod1>d__1.MoveNext() in ****:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

Partial of the MyDbContext:
```
public class MyDbContext : DbContext
{    
    public DbSet<User> Users { get; set; }

    private MyDbContext() : base()
    {
        this.Configuration.LazyLoadingEnabled = false;
    }

    private MyDbContext(DbConnection connection) : base(connection, true)
    {
        this.Configuration.LazyLoadingEnabled = false;
    }

    public static MyDbContext CreateDbContext(DbConnection connection = null)
    {
        if (connection == null)
           return new MyDbContext();

        return new MyDbContext(connection);
    }
}
```

This is the User Entity.
```
public class User
{
    
    [Key]
    public long Id { get; set; }

    [Required]
    [MaxLength(PropertyLengths.UserUsernameMax)]
    [MinLength(PropertyLengths.UserUsernameMin)]
    [Index(IsUnique = true)]
    public string Username { get; set; }

    [Required]
    [MaxLength(PropertyLengths.UserEmailMax)]
    [EmailAddress]
    [Index(IsUnique = true)]
    public string Email { get; set; }

    public DateTime RegistrationTime { get; set; }

    [Required]
    [MaxLength(PropertyLengths.UserPasswordBinaryMax)]
    public byte[] Password { get; set; }

    public bool IsSupaUza { get; set; }

    public virtual ICollection<SomeEntity1> SomeEntities1 { get; set; }

    public virtual ICollection<SomeEntity2> SomeEntities2 { get; set; }

    public virtual ICollection<SomeEntity3> SomeEntities3 { get; set; }

    [MaxLength(PropertyLengths.DefaultMax)]
    public string FirstName { get; set; }

    [MaxLength(PropertyLengths.DefaultMax)]
    public string LastName { get; set; }

    [Column(TypeName = "Date")]
    public DateTime DateOfBirth { get; set; }

    [MaxLength(PropertyLengths.BlobUri)]
    public string MyCoolPic { get; set; }     
}
```

Unit test project app.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework" />
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />      
    </providers>
  </entityFramework>  
</configuration>
```

Unit test project packages.config
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Effort.EF6" version="1.1.4" targetFramework="net45" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net45" />
  <package id="NMemory" version="1.0.1" targetFramework="net45" />
</packages>
```

**Comment by tompazourek** [comment]
I am experiencing the same issue and I have currently no idea what could cause it.

**Comment by kburnik** [comment]
We noticed this also happens when using SQLCE. The problem in that case was
with data type annotations. To be more precise it was occuring when the
column type was Date rather than DateTime (as I recall, but maybe it's vice
versa - so check). Didn't try it on Effort but it fixed SQLCE.

Please check if this fixes your problem and post back. I am curious to if
it is the cause for the Exception in Effort as well.

**Comment by tompazourek** [comment]
I simply removed the explicit "ntext" configuration from my entity type configuration:

    Property(x => x.DocumentationLinks)
                .HasColumnType("ntext");

After this, the property was mapped as `nvarchar(max)` instead (by default) and my problem was resolved, the rest of my model did not have any explicit `HasColumnType` configurations and Effort worked fine.

**Comment by tamasflamich** [comment]
Yes, this is a (common problem)[https://effort.codeplex.com/workitem/678] and unfortunately EF does not provide any helpful exception message.

I created a little (workaround)[http://1drv.ms/173VTu1] that tries to make this less painful.

**Comment by tamasflamich** [comment]
I used to dedicate a large amount of time searching for a robust solution. Unfortunately EF didn't make it easy, so I had to give up. Since probably EF7 will get most of the future focus, I am not planning to solve this issue.

**Comment by kburnik** [comment]
Do you suppose you could just add an instruction on the pages where people
get started with Effort?

E.G. at least here:
https://github.com/tamasflamich/effort/blob/master/README.md
and here: https://effort.codeplex.com/

I think it would rid them great pains in the future.

Something like:

*Things to watch out for - Data annotations and unsupported column types*

...






On Sat, May 16, 2015 at 12:57 PM, Tamas Flamich <notifications@github.com>
wrote:

> Closed #10 <https://github.com/tamasflamich/effort/issues/10>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tamasflamich/effort/issues/10#event-306437784>.
>



-- 
Pozdrav,
Kristijan Burnik

**Comment by tamasflamich** [comment]
This is a great idea, because probably many users encounter this issue. I will give it a shot.

**Comment by kburnik** [comment]
Great! :-)

++effort :-)

**Comment by nadavdrewe** [comment]
I think that would be a good idea - I also ran into this issue. A lot of people using this library will be using EF data annotations... Thx guys

**Comment by sdunnin** [comment]
Ran into this issue and am pretty much stuck. Tried creating a super simple entity with no annotations whatsoever but still fail when trying to Add via the db context.

Entity Class:
 public class Junk
    {
        public int Id { get; set; }
        public string Property1 { get; set; }
        public string Property2 { get; set; }
        public string Property3 { get; set; }
    }

Add Fails with System.InvalidOperationException: Sequence contains no matching element:
   DbConnection effortConnection = DbConnectionFactory.CreateTransient();
   using (var db = new PSSModelContainer(effortConnection))
            {
                db.Junky.Add(new Junk { Id=1,  Property1 = "1", Property2 = "2", Property3 = "3" });
                db.SaveChanges();
             }

The context class looks like
    public partial class PSSModelContainer : DbContext
    {
        public PSSModelContainer()
            : base("name=PSSModelContainer")
        {
        }
        public PSSModelContainer(System.Data.Common.DbConnection connection)
            : base(connection, true)
        {
        }
        public ObjectContext ObjectContext
        {
            get { return ((IObjectContextAdapter) this).ObjectContext; }
        }
        ...DbSet
        ...Fluent commands
}

**Comment by kburnik** [comment]
Did you try adding annotations?

E.G. [Key] for id?

On Wed, Jul 22, 2015 at 3:49 PM, sdunnin <notifications@github.com> wrote:

> Ran into this issue and am pretty much stuck. Tried creating a super
> simple entity with no annotations whatsoever but still fail when trying to
> Add via the db context.
>
> Entity Class:
> public class Junk
> {
> public int Id { get; set; }
> public string Property1 { get; set; }
> public string Property2 { get; set; }
> public string Property3 { get; set; }
> }
>
> Add Fails with System.InvalidOperationException: Sequence contains no
> matching element:
> DbConnection effortConnection = DbConnectionFactory.CreateTransient();
> using (var db = new PSSModelContainer(effortConnection))
> {
> db.Junky.Add(new Junk { Id=1, Property1 = "1", Property2 = "2", Property3
> = "3" });
> db.SaveChanges();
> }
>
> The context class looks like
> public partial class PSSModelContainer : DbContext
> {
> public PSSModelContainer()
> : base("name=PSSModelContainer")
> {
> }
> public PSSModelContainer(System.Data.Common.DbConnection connection)
> : base(connection, true)
> {
> }
> public ObjectContext ObjectContext
> {
> get { return ((IObjectContextAdapter) this).ObjectContext; }
> }
> ...DbSet
> ...Fluent commands
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tamasflamich/effort/issues/10#issuecomment-123728332>.
>



-- 
Pozdrav,
Kristijan Burnik

**Comment by sdunnin** [comment]
If I strip down my context class to have just the "Junk" DbSet property it works. The problem must lie somewhere in the many other entity sets defined in there. Interesting that EF would perform mapping behind the scenes for all of the entities when I'm only adding to a specific one.

**Comment by sdunnin** [comment]
Also, our entities use many data annotations so I fear that it would be a long tedious process sifting through them to find which ones are problematic for EF using Effort.

**Comment by sdunnin** [comment]
Adding a simple [Key] annotation to the Junk entity works fine.

**Comment by sdunnin** [comment]
I believe that I narrowed down the problem to 4 entities have a [Column(TypeName = "date")] attribute. If I comment out the attribute it works.

I presume that I could try the workaround noted above to handle that mapping error.

**Comment by kburnik** [comment]
I believe my team ended up removing those annotations. But I didn't go into
details on how it was solved.

On Wed, Jul 22, 2015 at 4:35 PM, sdunnin <notifications@github.com> wrote:

> I believe that I narrowed down the problem to 4 entities have a
> [Column(TypeName = "date")] attribute. If I comment out the attribute it
> works.
>
> I presume that I could try the workaround noted above to handle that
> mapping error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tamasflamich/effort/issues/10#issuecomment-123743270>.
>



-- 
Pozdrav,
Kristijan Burnik

**Comment by emragins** [comment]
Just throwing in my experience...
This caused the error:

`Property(x => x.IsArchived).HasColumnName("IsArchived").IsRequired().HasColumnType("boolean");`

This did not:

`Property(x => x.IsArchived).HasColumnName("IsArchived").IsRequired().HasColumnType("bit");`

**Comment by nielshede** [comment]
I have submitted a pull request that solves this issue.

**Comment by mirogrenda** [comment]
I also ran into this issue - caused by [Column(TypeName = "ntext")].

**Comment by testfirstcoder** [comment]
Same problem with Property(_ => _.PropertyName).HasColumnType("char"). 

So use Property(_ => _.PropertyName).IsFixedLength().IsUnicode(false) instead.

**Comment by jimmymain** [comment]
Same problem with 
```
[Column(TypeName = "varbinary(max)")]
```
Have elected to ignore that property for unit tests.
```
// my hack...
if (this.Database.Connection.GetType().Name.StartsWith("Effort", StringComparison.Ordinal))
{
    modelBuilder.Entity<Building>().Ignore(_ => _.Geolocation);
    modelBuilder.Entity<AttachedDocument>().Ignore(_ => _.Contents);
}

**Comment by amantur** [comment]
baaa I just wasted about an hour with this.l In the end it was type. :(

"smalldateteime" instead of "smalldatetime"

**Comment by ozwaldDunlop** [comment]
This problem also occurs for xml column type. putting a check for Effort around it like @jimmymain [https://github.com/tamasflamich/effort/issues/10#issuecomment-228719218](https://github.com/tamasflamich/effort/issues/10#issuecomment-228719218)
```
if (!this.Database.Connection.GetType().Name.StartsWith("Effort", StringComparison.Ordinal))
{
    Property(x => x.XMLData).HasColumnType("xml");
}
```

**Comment by General-Fault** [comment]
I'm using the "EntityFramework Reverse POCO Code First Generator" tool on a SQL Server database. The generated code adds "nvarchar" column type configuration, which is resulting in this same error.

`Property(x => x.EventClassName).HasColumnName(@"EventClassName").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);`

Unfortuantely I have far too many nvarchar columns to do what @ozwaldDunlop suggests.

What if there were a way to easily specify a custom EffortProviderManifest.xml in which we could add types that are not supported by default?

**Comment by jimmyjlli** [comment]
I'm also using "EntityFramework Reverse POCO Code First Generator" and hitting similar problem. Is there a solution/good-workaround for this?

**Comment by dougajmcdonald** [comment]
I'd be really keen to find a solution to this problem. Neither effort nor EF seem to help us identify which columns could be the problem

**Comment by ariovistus** [comment]
workaround link appears to be broken, anyone have a working one?

**Comment by beanian** [comment]
> I'm also using "EntityFramework Reverse POCO Code First Generator" and hitting similar problem. Is there a solution/good-workaround for this?
I'm in the same boat...any joy with this?

**Comment by zalos** [comment]
I removed all .HasColumnType("ANY FIELD HERE"), and it worked for me. 

I think our solution will be to have our generator from the database create one with and one without and use the other / if statement out the column types like the above examples show.
