### ISSUE TITLE
Can Effort not be used with Code-First?

### ISSUE THREAD

**Issue by togakangaroo** [tamasflamich/effort#13]
This is more of a discussion item, but I don't really see any solid examples anywhere on how to use Effort with a code first context. I tried just creating a `MyDbContext` as in one of the tutorials, but none of its `IDbSet<>` properties get populated.

So I guess can you let me know if this is a limitation (and document it on the site) or give me a hint as to how it can be done (and document it).

I can try to help a bit with the documentation bit if I understand how this is intended to work.

**Comment by tamasflamich** [comment]
It can work perfectly fine with `DbContext` as well. Which tutorial are you referring to exactly, [this](http://effort.codeplex.com/wikipage?title=Create%20a%20fake%20DbContext%20instance&referringTitle=Tutorials) one?

**Comment by togakangaroo** [comment]
Yes exactly, When I tried this I found that my `IDbSets` were still null

**Comment by tamasflamich** [comment]
Strange, because `DbContext` is a first class citizen. Do you use the `DbConnection` or `EntityConnection` approach? The later requires a properly setup edmx file as well.

**Comment by togakangaroo** [comment]
It was a DbConnection. I'll try again, is a DbContext constructor supposed to scan the class and populate the `IDbSet` instances then?

**Comment by tamasflamich** [comment]
Yea, it should.

**Comment by voroninp** [comment]
Hello. Is there any reason why ProviderManifest.xml does not have types like "date", "datetime2" ?
