### ISSUE TITLE
Testing code using Microsoft.AspNet.Identity.EntityFramework.* things

### ISSUE THREAD

**Issue by Dashue** [tamasflamich/effort#16]
Hey, hope you'd be able to help me out here as I cannot figure out a solution.

Setup in tests:

    _kernel.Rebind<DbConnection>().ToConstant(Effort.DbConnectionFactory.CreateTransient());

Context:

    public class MyDbContext : IdentityDbContext<MyApplicationUser>
    {
        public MyDbContext()
            : base("DefaultConnection", false)
        {
    	    // This is version I want to start injecting dbconnection into, like below
    	    // <add name="DefaultConnection" connectionString="data source=localhost;initial catalog=MyDbTable;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework" providerName="System.Data.SqlClient" />
        }

        public MyDbContext(DbConnection connection)
            : base(connection.ConnectionString, false)
        {
            Console.WriteLine(connection.ConnectionString); // instanceid=0c8baee5-5790-4b37-9772-49fe7da75f43
        }
    }

Result:

    System.ArgumentException: Keyword not supported: 'instanceid'.

Thanks for your time and "Effort" :)

**Comment by kevin-work** [comment]
+1

**Comment by tamasflamich** [comment]
Hi @Dashue - Sorry for the late response. For others who encounter this issue:

If I remember correctly `IdentityDbContext` has a constructor that accepts `DbConnection` instances as arguments. You should use this as the base constructor for `MyDbContext(DbConnection connection)`
