### ISSUE TITLE
Can Effort be used with ADO.NET directly? (e.g. for Dapper)

### ISSUE THREAD

**Issue by geirsagberg** [tamasflamich/effort#23]
I understand that Effort is mainly targeted towards Entity Framework-applications, but an in-memory database would be nice to have in other applications as well.

I am working on an application that uses Dapper with a ADO.NET IDbConnection and would like to use Effort to run database tests. Is this possible / intended?

**Comment by tamasflamich** [comment]
No, this is not possible. The underlying database is NMemory that uses .net expression trees for defining, compiling and executing queries. When you query something with Entity Framework it builds another type of expression tree that ADO.NET providers have to convert into SQL commands. Effort is basically an ADO.NET provider as converts these EF expression trees into .net expression trees [under the hood](https://github.com/tamasflamich/effort/tree/develop/Main/Source/Effort/Internal/DbCommandTreeTransformation) that can be passed to NMemory.

If we wanted to make Effort purely ADO.NET compatible, someone should make it able to interpret SQL commands. This is a much more complex problem than being able to convert EF expression trees and I will certainly not have time to dedicate on this.

**Comment by geirsagberg** [comment]
Roger that, I understand that this would be quite a complex endeavour. Too bad that there isn't any in-memory SQL-compliant database for .NET, something like HSQLDB for Java. I ended up using [SqlLocalDb](https://github.com/martincostello/sqllocaldb), not as fast as in-memory but supports SQL.
