### ISSUE TITLE
Possible TVP in stored procedure support?

### ISSUE THREAD

**Issue by Dashue** [tamasflamich/effort#25]
Hey, was just converting a bit of logic using this approach
http://misterunconditional.com/tvpextensions/ and ended up encountering "System.ArgumentException: The provided parameter object is incompatible"

Is this supported, or would it be easy to add support for it?

Thanks!

**Comment by tamasflamich** [comment]
Hi @Dashue - Stored procedures are not supported by Effort and it will probably never be as it would require way to much work: deep migrations support, database specific sp parser and execution engine. Even if it existed the feature would be probably too confusing for the library users.
