### ISSUE TITLE
Effort.EF6 with MigrateDatabaseToLatestVersion

### ISSUE THREAD

**Issue by Gwynnbleid1** [tamasflamich/effort#26]
Hi! 

Is it possible to use effort with MigrateDatabaseToLatestVersion database Initializer? 
I have a project which use it with initializer defined like this:

```
  static LibraryContext()
        {
                Database.SetInitializer(new MigrateDatabaseToLatestVersion<LibraryContext, Configuration>());
        }
```
In migrations Up method there are also sql queries with static data (I don't use a Seed method in Configuration class). Problem is that effort can't initialize the dabase: 
Test Name: GetBook_WithNonExistingId_ReturnsNull 
Test FullName: Testy_Jednostkowe.BookRepositoryTests.GetBook_WithNonExistingId_ReturnsNull 
Test Source: d:\documents\visual studio 2015\Projects\Testowanie_EF6_Wlaczone_Migracje\Testy_Jednostkowe\BookRepositoryTests.cs : line 28 
Test Outcome: Failed 
Test Duration: 0:00:04,6449765 

Result StackTrace: 
w Effort.Internal.DbManagement.DbContainer.get_Internal() 
w Effort.Internal.DbManagement.DbContainer.GetTable(String name) 
w Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbScanExpression expression) 
w System.Data.Entity.Core.Common.CommandTrees.DbScanExpression.Accept[TResultType](DbExpressionVisitor1 visitor) 
w Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression) 
w Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbFilterExpression expression)
w System.Data.Entity.Core.Common.CommandTrees.DbFilterExpression.Accept[TResultType](DbExpressionVisitor1 visitor) 
w Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression) 
w Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbLimitExpression expression) 
w System.Data.Entity.Core.Common.CommandTrees.DbLimitExpression.Accept[TResultType](DbExpressionVisitor1 visitor) 
w Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression) 
w Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbProjectExpression expression) 
w System.Data.Entity.Core.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor1 visitor) 
w Effort.Internal.DbCommandTreeTransformation.TransformVisitor.Visit(DbExpression expression) 
w Effort.Internal.CommandActions.QueryCommandAction.ExecuteDataReader(ActionContext context) 
w Effort.Provider.EffortEntityCommand.ExecuteDbDataReader(CommandBehavior behavior) 
w System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior) 
w System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c__DisplayClassb.<Reader>b__8() 
w System.Data.Entity.Infrastructure.Interception.InternalDispatcher1.Dispatch[TInterceptionContext,TResult](Func1 operation, TInterceptionContext interceptionContext, Action1 executing, Action1 executed) 
w System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext) 
w System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior) 
w System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior) 
w System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior) 
--- End of inner exception stack trace ---
w System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
w System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues) 
w System.Data.Entity.Core.Objects.ObjectQuery1.<>c__DisplayClass3.<GetResults>b__2() 
w System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess) 
w System.Data.Entity.Core.Objects.ObjectQuery1.<>c__DisplayClass3.<GetResults>b__1() 
w System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func1 operation) 
w System.Data.Entity.Core.Objects.ObjectQuery1.GetResults(Nullable1 forMergeOption) 
w System.Data.Entity.Core.Objects.ObjectQuery1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0() 
w System.Lazy1.CreateValue() 
w System.Lazy1.LazyInitValue() 
w System.Lazy1.get_Value() 
w System.Data.Entity.Internal.LazyEnumerator1.MoveNext() 
w System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable1 source) 
w System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__2[TResult](IEnumerable1 sequence) 
w System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable1 query, Expression queryRoot) 
w System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression) 
w System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression) 
w System.Linq.Queryable.SingleOrDefault[TSource](IQueryable1 source, Expression1 predicate) 
w Baza.BookRepository.Get(Int32 id) w d:\documents\visual studio 2015\Projects\Testowanie_EF6_Wlaczone_Migracje\Baza\BookRepository.cs:wiersz 16 
w Testy_Jednostkowe.BookRepositoryTests.GetBook_WithNonExistingId_ReturnsNull() w d:\documents\visual studio 2015\Projects\Testowanie_EF6_Wlaczone_Migracje\Testy_Jednostkowe\BookRepositoryTests.cs:wiersz 33 
Result Message: 
Test method Testy_Jednostkowe.BookRepositoryTests.GetBook_WithNonExistingId_ReturnsNull threw exception: 
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> Effort.Exceptions.EffortException: Database has not been initialized. 

If using CodeFirst try to add the following line: 
context.Database.CreateIfNotExists()

**Comment by voroninp** [comment]
Actually, I have this exception on `SaveChanges()` call with any other initializer.

**Comment by tamasflamich** [comment]
Hey @voroninp - You should disable migrations for your tests that are using Effort as the library doesn't support it. I understand that this is a bit inconvenient, but imo not that hard to do.

**Comment by tamasflamich** [comment]
Potential useful link:
http://stackoverflow.com/questions/14654055/how-can-i-disable-code-first-migrations

**Comment by Defee** [comment]
None of the suggestion in stackoverflow didn't help. I have even deleted migrations folder, Forced migrations not to initialize for that context. Have you got any other suggestions? It is kind of weird...

**Comment by nathfy** [comment]
More info for those googling the issue: 
http://stackoverflow.com/questions/34701550/entity-framework-6-throws-migration-exception-when-trying-to-create-a-context-wi

**Comment by Eagle3386** [comment]
Using EF 6.2.0 and Effort.EF6 1.3.0, I seem unable to disable migrations successfully: while my unit test runs perfectly on my machine, the build server always fails on `AddOrUpdate()` of my seed method, stating:

Initialization method MyApp.Testing.MyAppTests.Initialize threw exception. System.Data.Entity.Migrations.Infrastructure.MigrationsException: System.Data.Entity.Migrations.Infrastructure.MigrationsException: No MigrationSqlGenerator found for provider 'Effort.Provider'. Use the SetSqlGenerator method in the target migrations configuration class to register additional SQL generators.

Below you'll find the relevant code snippets.
Any help is greatly appreciated as I tried to fix this for hours without any luck.. 🙁 

**App.config:**
```xml
<configSections>
  <section name="entityFramework" (...) />
</configSections>
<connectionStrings>
  <clear />
  <add name="Local" connectionString="Data Source=localhost;Initial Catalog=MyDb;Integrated Security=True;MultipleActiveResultSets=True;App=EntityFramework" />
  <!--add name="Test system" connectionString="Data Source=db-server;Initial Catalog=MyDbTest;Integrated Security=True;MultipleActiveResultSets=True;App=EntityFramework" /-->
</connectionStrings>
<system.data>
  <DbProviderFactories>
    <add name="Effort.Provider" invariant="Effort.Provider" description="Effort.Provider" type="Effort.Provider.EffortProviderFactory, Effort" />
  </DbProviderFactories>
</system.data>
<entityFramework>
  <providers>
    <!--provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" /-->
    <provider invariantName="Effort.Provider" type="Effort.Provider.EffortProviderServices, Effort" />
  </providers>
  <contexts>
    <context type="MyApp.Data.MyDbContext, MyApp.Data" disableDatabaseInitialization="true" />
  </contexts>
  <defaultConnectionFactory type="MyApp.Testing.EffortProviderFactory, MyApp.Testing" />
</entityFramework>
```
**MyAppTests.cs:**
```csharp
[TestInitialize]
public void Initialize()
{
  TestDatabase.PrepareData();
  // ... 
}
```
**TestDatabase.cs:**
```csharp
public static void PrepareData()
{
  EffortProviderFactory.ResetDb();
  using (var scope = MyDbContextScopeFactory.Create())
  {
    var context = scope.DbContexts.Get<MyDbContext>();
    context.Database.CreateIfNotExists();
    MyContextSeed.SeedMyContext(context);
    context.SaveChanges();
  }
  //...
}
```

**MyContextSeed.cs:**
```csharp
public static void SeedMyContext(MyDbContext context)
{
  context.Countries.AddOrUpdate(c => c.Code, new Country { Code = "Foo", Name = "Fooland" }, new Country { Code = "Bar", Name = "Barsea" });
  context.SaveChanges();
  //...
}
```

**Note: Crash happens on `AddOrUpdate()`, not on `SaveChanges()`!**
