### ISSUE TITLE
Stored procedure

### ISSUE THREAD

**Issue by alphaCoder** [tamasflamich/effort#32]
Hey tamasflamich,

I have a stored procedure which will return id generated from db. I was wondering if there is any way to mock this stored procedure call using Effort. I have in memory Id generator but I don't see a documentation how to inject this whenever store procedure is called.

My apologies if my question doesn't make sense.

Thanks

**Comment by tamasflamich** [comment]
Hi @alphaCoder - Effort doesn't support faking stored procedures. I am not entirely sure how you currently utilize them, but I'd suggest to create fake calls on application level and not ORM level.

**Comment by djavier** [comment]
@tamasflamich I think is issue should be close, its clearly no in the scope of *Effort*.

**Comment by alphaCoder** [comment]
@tamasflamich sorry for late response, yes I am doing exactly same faking at application level.

Thank you.
