### ISSUE TITLE
Support EF 6.1.2

### ISSUE THREAD

**Issue by Suriman** [tamasflamich/effort#4]
Effort is not currently support Entity Framework 6.1.2.

**Comment by tamasflamich** [comment]
Oh god, they just broke a public interface.

**Comment by tamasflamich** [comment]
I fixed the issue, thank you for reporting.
https://www.nuget.org/packages/Effort.EF6/

**Comment by hikalkan** [comment]
Thank you so much.

**Comment by hikalkan** [comment]
Hi again,

After upgrading, I got that error:

System.IO.FileLoadExceptionCould not load file or assembly 'Effort, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6a46696d54971e6d' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key.

Is it happing just for me?

**Comment by tamasflamich** [comment]
Ups, the assembly was not signed. I just released a new version.

**Comment by hikalkan** [comment]
Thanks a lot. It worked :)

**Comment by Suriman** [comment]
It's OK.Thank you very much!.
Happy New Year!
