### ISSUE TITLE
AmbiguousMatchException when enumerating DbSet.

### ISSUE THREAD

**Issue by voroninp** [tamasflamich/effort#41]
Effort throws `AmbiguousMatchException`  when calling  `DbSet.ToList()`.

We've discovered the cause of this behavior: 
There are two entities which are mapped to tables with similar names: `WUBS.InstructionStatus` and `APN.InstructionStatus`. The only difference is namespace. Whenever we change the name of either of the table everything works fine.

**Comment by tamasflamich** [comment]
Hi voroninp - Sorry for the very late response, this seems to replicate #50
