### ISSUE TITLE
Support for same named tables across multiple schemas

### ISSUE THREAD

**Issue by kerryarts** [tamasflamich/effort#50]
I am running into an issue whereby I have two tables with the same table name, but in different schemas.
This works fine against a real database, with the only limitation being that EF require the two entity classes to have different names.

From what I can gather, Effort ends up partially merging the two table definitions together inside of `Effort.Internal.DbManagement.CanonicalContainer.GetEntities()`.

Poking around a bit, a solution might be as simple as changing `Effort.Internal.Common.EdmHelper.GetTableName()` to prepend the scheama name to the table name, but I am not sure of the implications of this.

**Comment by tamasflamich** [comment]
Hi kerryarts - great, you just figured out the cause yourself! Your proposal should probably do the trick, and I am really happy to accept this as a contribution.

**Comment by tamasflamich** [comment]
It turned out to be a "bit" more complicated, but it's done.
https://github.com/tamasflamich/effort/commit/9bced9e9ba5c5a9c3a7c525f1d873afb1fc5494d

**Comment by kerryarts** [comment]
Oh wow thats awesome thanks, nice _effort_!

**Comment by kerryarts** [comment]
@tamasflamich Whats your nuget release process? Are we able to get a bug fix release with this change?

**Comment by tamasflamich** [comment]
Hey @kerryarts - just released a new version of the lib:
https://www.nuget.org/packages/Effort.EF6/1.3.0
