### ISSUE TITLE
Any plans to port this to .NET Core?

### ISSUE THREAD

**Issue by brunchey** [tamasflamich/effort#51]
Love the library!  Wondering what plans (if any) were already in place for porting this to .NET Core?

**Comment by tamasflamich** [comment]
Hi brunchey - Nope. I currently don't have any intention to do any development on this lib anymore besides bug fixes. Afaik EF Core has a [builtin feature](https://docs.efproject.net/en/latest/miscellaneous/testing.html) to provide the functionality of this lib.

**Comment by dmasur** [comment]
Hi tamas,

both EF Core options are suboptimal.
- SQL Lite throws not very useful error messages from its core for simple stuff: https://github.com/aspnet/Microsoft.Data.Sqlite/issues/174
- The InMemory Db miss many features like validation

I think Effort would be a great addition to this list.

Do you see big problems in porting Effort to .Net Standard?

**Comment by JonathanMagnan** [comment]
Hello @dmasur ,

We will for sure try to port `Effort` to .NET Standard but I don't think it will come in the next following month as we have some free library we want to improve first such as [Entity Framework Plus](http://entityframework-plus.net/)

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
